custom: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/githubRummy.apk
polar: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/JaldiRummy.apk
github: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/JaldiRummy.apk
