buy_me_a_coffee: https://github.com/deepakrummy/deepakrummy.github.io/blob/main/JaldiRummy.apk
custom: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/JaldiRummy.apk
