custom: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/githubRummy.apk
buy_me_a_coffee: https://downgit.github.io/#/home?url=https://github.com/deepakrummy/deepakrummy.github.io/blob/main/JaldiRummy.apk
[![paypal](https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif)](fisherrambo5@gmail.com)
